version: 1.0.0
ignore:
  - id: endorignore-1
    username: osircar@endor.ai@google
    update_time: 2026-07-27 14:02:05 UTC
    dependency_name: go://github.com/dgrijalva/jwt-go@v3.2.0+incompatible
    vuln_id: GHSA-w73w-5m7g-f7qc
    reason: risk-accepted
    comments: I want this gone!
  - id: endorignore-2
    username: osircar@endor.ai@google
    update_time: 2026-08-06 03:34:24 UTC
    finding_name: 'CVE-2023-7104:'
    vuln_id: CVE-2023-7104
    reason: risk-accepted
    comments: Not not dude
  - id: endorignore-3
    username: osircar@endor.ai@google
    update_time: 2026-08-11 06:07:18 UTC
    finding_name: 'Potential secret leak Asana Client Secret: ID #c83dfc'
    extra_key: '675bc43b43e88b87ac468111Asana Client Secret: ID #c83dfc'
    reason: risk-accepted
