version: 1.0.0
ignore:
  - id: endorignore-1
    username: osircar@endor.ai@google
    update_time: 2026-07-27 14:02:05 UTC
    dependency_name: go://github.com/dgrijalva/jwt-go@v3.2.0+incompatible
    vuln_id: GHSA-w73w-5m7g-f7qc
    reason: risk-accepted
    comments: I want this gone!
  - id: endorignore-2
    username: osircar@endor.ai@google
    update_time: 2026-08-06 03:34:24 UTC
    finding_name: 'CVE-2023-7104:'
    vuln_id: CVE-2023-7104
    reason: risk-accepted
    comments: Not not dude
  - id: endorignore-3
    username: osircar@endor.ai@google
    update_time: 2026-08-11 10:14:19 UTC
    finding_name: 'Potential secret leak Generic API Key: ID #c3a16a'
    reason: false-positive
    comments: '"Remove this secret as it is a secret no more!'
  - id: endorignore-4
    username: osircar@endor.ai@google
    update_time: 2026-08-11 16:53:17 UTC
    finding_name: 'Potential secret leak Asana Client Secret: ID #c83dfc'
    reason: false-positive
  - id: endorignore-5
    username: osircar@endor.ai@google
    update_time: 2026-08-11 16:53:40 UTC
    finding_name: 'Code Injection - Non-static command detected inside `exec.Cmd`: ID #f49b48'
    reason: risk-accepted
  - id: endorignore-6
    username: osircar@endor.ai@google
    update_time: 2026-08-12 02:57:11 UTC
    finding_name: 'Code Injection - Non-static command detected inside `exec.Cmd`: ID #75cd15'
    reason: risk-accepted
  - id: endorignore-7
    username: osircar@endor.ai@google
    update_time: 2026-08-12 03:03:21 UTC
    finding_name: 'Code Injection - Non-static command detected inside `exec.Cmd`: ID #8ca367'
    reason: risk-accepted
  - id: endorignore-8
    username: osircar@endor.ai@google
    update_time: 2026-08-12 03:08:59 UTC
    finding_name: Use of Hard-coded Credentials
    reason: risk-accepted
  - id: endorignore-9
    username: osircar@endor.ai@google
    update_time: 2026-08-12 03:31:22 UTC
    finding_name: 'Code Injection - Non-static command detected inside `exec.Cmd`: ID #49467d'
    reason: risk-accepted
  - id: endorignore-10
    username: osircar@endor.ai@google
    update_time: 2026-08-12 04:54:52 UTC
    finding_name: 'Code Injection - Non-static command detected inside `exec.Cmd`: ID #76e016'
    reason: risk-accepted
  - id: endorignore-11
    username: osircar@endor.ai@google
    update_time: 2026-08-12 07:25:14 UTC
    finding_name: 'Code Injection - Non-static command detected inside `exec.Cmd`: ID #9cac06'
    reason: risk-accepted

